
name: Publish to Docker Hub

on:
  push:
    branches: 
      - '*'
    tags:
      - '*'

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: docker build -t mendhak/test-image .
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: echo the tag
        run: echo ${{ steps.get_version.outputs.VERSION }}
      # - name: Push to Docker Hub
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: mendhak/test-image:${{ env.TAG }}