
name: Publish to Docker Hub

on:
  push:
    branches: 
      - '*'
    tags:
      - '*'

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the image
        run: docker build -t mendhak/http-https-echo:latest .
